ifeq ($(findstring 86, $(ProgramFiles)), )
	PROGFILES := C:/Program Files
else
	PROGFILES := C:/Program Files (x86)
endif

GNU_INSTALL_ROOT :=C:\Program Files (x86)\GNU Tools ARM Embedded\5.2 2015q4
GNU_VERSION := 5.2 2015q4
GNU_PREFIX := arm-none-eabi

